<?xml version="1.0"?>
<!DOCTYPE config [
<!ELEMENT config (rom_path?, gamelist?, backup_path?, width?, height?, fullscreen?, fps_limit?)>
	<!ELEMENT rom_path (#PCDATA)>
	<!ELEMENT gamelist (#PCDATA)>
	<!ELEMENT backup_path (#PCDATA)>
	<!ELEMENT width (#PCDATA)>
	<!ELEMENT height (#PCDATA)>
	<!ELEMENT fullscreen (#PCDATA)>
	<!ELEMENT fps_limit (#PCDATA)>
]>

<config>
	<rom_path>c:\devmame\roms</rom_path>
	<gamelist>games.xml</gamelist>
	<backup_path>c:\code\supermodel2\backup</backup_path>
	<width>1280</width>
	<height>1024</height>
	<fullscreen>yes</fullscreen>
	<fps_limit>no</fps_limit>
	<stretch>yes</stretch>
</config>