<?xml version="1.0"?>
<!DOCTYPE gamelist [
<!ELEMENT gamelist (game+)>
	<!ATTLIST gamelist>
	<!ELEMENT game (description, year?, manufacturer, step, bridge?, cromsize?, rom*, patch*, input*)>
		<!ATTLIST game name CDATA #REQUIRED>
		<!ATTLIST game parent CDATA #IMPLIED>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT manufacturer (#PCDATA)>
		<!ELEMENT step (#PCDATA)>
		<!ELEMENT bridge (#PCDATA)>
		<!ELEMENT cromsize (#PCDATA)>
		<!ELEMENT rom EMPTY>
			<!ATTLIST rom type CDATA #REQUIRED>
			<!ATTLIST rom name CDATA #REQUIRED>
			<!ATTLIST rom size CDATA #REQUIRED>
			<!ATTLIST rom crc CDATA #REQUIRED>
			<!ATTLIST rom sha1 CDATA #IMPLIED>
		<!ELEMENT patch EMPTY>
			<!ATTLIST patch size CDATA #REQUIRED>
			<!ATTLIST patch address CDATA #REQUIRED>
			<!ATTLIST patch data CDATA #REQUIRED>
		<!ELEMENT input EMPTY>
			<!ATTLIST input type CDATA #REQUIRED>
			<!ATTLIST input center CDATA #IMPLIED>
			<!ATTLIST input mapping CDATA #REQUIRED>
]>

<gamelist>
	<game name="vf3">
		<description>Virtua Fighter 3</description>
		<year>1996</year>
		<manufacturer>Sega</manufacturer>
		<step>1.0</step>
		
		<input type="button01" mapping="p1_button_1"/>
		<input type="button02" mapping="p1_button_2"/>
		<input type="button03" mapping="p1_button_3"/>
		<input type="button04" mapping="p1_button_4"/>
		<input type="button05" mapping="p1_joystick_up"/>
		<input type="button06" mapping="p1_joystick_down"/>
		<input type="button07" mapping="p1_joystick_right"/>
		<input type="button08" mapping="p1_joystick_left"/>
		
		<patch size="32" address="7125b0" data="60000000"/>
		<patch size="32" address="7125d0" data="60000000"/>
		<patch size="32" address="72e97c" data="60000000"/>		<!-- waits for decrementer == 0 -->
		<patch size="32" address="72e99c" data="60000000"/>		<!-- waits for decrementer -->
		
		<rom type="prog0" name="epr-19227c.17" size="524288" crc="a7df4d75" sha1="1b1186227f830556c5e2b6ca4c2bf20673b22f94"/>
		<rom type="prog1" name="epr-19228c.18" size="524288" crc="9c5727e2" sha1="f9f8b8cf27fdce08ab2975dbaa8c7a03f5c064fb"/>
		<rom type="prog2" name="epr-19229c.19" size="524288" crc="731b6b78" sha1="e39f92f721c2771f2d1f5b67625659e006f6fe0a"/>
		<rom type="prog3" name="epr-19230c.20" size="524288" crc="736a9431" sha1="0f62a122f349c0b0aab43863a30284a8fe4b7ba9"/>
		<rom type="crom00" name="mpr-19193.1" size="4194304" crc="7bab33d2" sha1="243a09959f3c4311070f1de760ee63958cd47660"/>
		<rom type="crom01" name="mpr-19194.2" size="4194304" crc="66254702" sha1="843ac4f6791f312f3138f8f38d38c8e4d2bab305"/>
		<rom type="crom02" name="mpr-19195.3" size="4194304" crc="bd5e27a3" sha1="778c67bf7b5c7e3ae52fe12308a81b095563f52b"/>
		<rom type="crom03" name="mpr-19196.4" size="4194304" crc="f386b850" sha1="168d21382359acb8f1d52d722de8c6b9a9210378"/>
		<rom type="crom10" name="mpr-19197.5" size="4194304" crc="a22d76c9" sha1="ad2d67a62436ccc6479e2a218ab09d2fc22c367d"/>
		<rom type="crom11" name="mpr-19198.6" size="4194304" crc="d8ee5032" sha1="3e9274142874ace76dba2bc9b5351cfdfb3a50cd"/>
		<rom type="crom12" name="mpr-19199.7" size="4194304" crc="9f80d6fe" sha1="97b9076d413e28d00e9c45fcc7dad6f534ca8874"/>
		<rom type="crom13" name="mpr-19200.8" size="4194304" crc="74941091" sha1="914db3955f355779147d86446f5976121191ea6d"/>
		<rom type="crom20" name="mpr-19201.9" size="4194304" crc="7c4a8c31" sha1="473b7bef932d7d54a5dc06bd80d286f2e2e96d44"/>
		<rom type="crom21" name="mpr-19202.10" size="4194304" crc="aaa086c6" sha1="01871c8e5454aed80e907fde199cfb23a57aa1c2"/>
		<rom type="crom22" name="mpr-19203.11" size="4194304" crc="0afa6334" sha1="1bb70e823fb6e05df069cbfafed2e57bda8776b9"/>
		<rom type="crom23" name="mpr-19204.12" size="4194304" crc="2f93310a" sha1="3dfc5b72a78967d7772da4098adb41f18b5294d4"/>
		<rom type="crom30" name="mpr-19205.13" size="4194304" crc="199c328e" sha1="1ef1f09ff1f5253bf03e06c5b6e42be9599b9ea5"/>
		<rom type="crom31" name="mpr-19206.14" size="4194304" crc="71a98d73" sha1="dda617f9f5f986e3369fa3d3090c423eefdf913c"/>
		<rom type="crom32" name="mpr-19207.15" size="4194304" crc="2ce1612d" sha1="736f559d460f0069c7a2d5ba7cddf9135737d6e2"/>
		<rom type="crom33" name="mpr-19208.16" size="4194304" crc="08f30f71" sha1="393525b19cdecddfbd62c6209203db5f3edfd9a8"/>
		<rom type="vrom00" name="mpr-19211.26" size="2097152" crc="9c8f5df1" sha1="d47c8bd0189c8e617a3ed9f75ee3812a229f56c0"/>
		<rom type="vrom01" name="mpr-19212.27" size="2097152" crc="75036234" sha1="01a20a6a62408017bff8f2e76dbd21c00275bc70"/>
		<rom type="vrom02" name="mpr-19213.28" size="2097152" crc="67b123cf" sha1="b84c4f83c25edcc8ac929d3f9cf51da713045071"/>
		<rom type="vrom03" name="mpr-19214.29" size="2097152" crc="a6f5576b" sha1="e994b3ef8e6eb07e8f3bbe474410c06d6c42354b"/>
		<rom type="vrom04" name="mpr-19215.30" size="2097152" crc="c6fd9f0d" sha1="1f3299706d6ac73836c069a7ed2866d412f60369"/>
		<rom type="vrom05" name="mpr-19216.31" size="2097152" crc="201bb1ed" sha1="7ffd72ff56159529d74f01f8da0ba4798f109806"/>
		<rom type="vrom06" name="mpr-19217.32" size="2097152" crc="4dadd41a" sha1="7a1e0908962afcfc737132478c0e45d153d94ecb"/>
		<rom type="vrom07" name="mpr-19218.33" size="2097152" crc="cff91953" sha1="41e95704a65958377c3bbd9d00d90a5ad4552f66"/>
		<rom type="vrom10" name="mpr-19219.34" size="2097152" crc="c610d521" sha1="cb146fe78d89176e9dd5c773644614cdc2ef57ce"/>
		<rom type="vrom11" name="mpr-19220.35" size="2097152" crc="e62924d0" sha1="4d1ac11a5977a4e9cf942c9f1204960c0a895347"/>
		<rom type="vrom12" name="mpr-19221.36" size="2097152" crc="24f83e3c" sha1="c587428fa47e849881bf45487af086db6b09264e"/>
		<rom type="vrom13" name="mpr-19222.37" size="2097152" crc="61a6aa7d" sha1="cc26020b2f904f68822111073b595ee0cc8b2e0c"/>
		<rom type="vrom14" name="mpr-19223.38" size="2097152" crc="1a8c1980" sha1="43b8efb019c8a20fe38f95050fe60dfe9bf322f0"/>
		<rom type="vrom15" name="mpr-19224.39" size="2097152" crc="0a79a1bd" sha1="1df71cf77ea8611462380a449eb99199664b3da3"/>
		<rom type="vrom16" name="mpr-19225.40" size="2097152" crc="91a985eb" sha1="5a842a260e4a78f5463222db44f13b068fa70b23"/>
		<rom type="vrom17" name="mpr-19226.41" size="2097152" crc="00091722" sha1="ef86db36b4b91a66b3e401c3c91735b9d28da2e2"/>
		<rom type="sprog" name="epr-19231.21" size="131072" crc="f2ae2558" sha1="7ab5fc508ffd1b0c9f3e70f4d3edeae44e3a0dc4"/>
		<rom type="srom0" name="mpr-19209.22" size="4194304" crc="3715e38c" sha1="b11dbf8a5840990e9697c53b4796cd70ad91f6a1"/>
		<rom type="srom1" name="mpr-19210.24" size="4194304" crc="c03d6502" sha1="4ca49fe5dd5105ca5f78f4740477beb64137d4be"/>
	</game>
	<game name="vf3tb" parent="vf3">
		<description>Virtua Fighter 3 Team Battle</description>
		<year>1996</year>
		<manufacturer>Sega</manufacturer>
		<step>1.0</step>
		
		<input type="button01" mapping="p1_button_1"/>
		<input type="button02" mapping="p1_button_2"/>
		<input type="button03" mapping="p1_button_3"/>
		<input type="button04" mapping="p1_button_4"/>
		<input type="button05" mapping="p1_joystick_up"/>
		<input type="button06" mapping="p1_joystick_down"/>
		<input type="button07" mapping="p1_joystick_right"/>
		<input type="button08" mapping="p1_joystick_left"/>
		
		<rom type="prog0" name="epr-20126.17" size="524288" crc="27ecd3b0" sha1="a9b913294ac925adb501d3b47f346006b70dfcd6"/>
		<rom type="prog1" name="epr-20127.18" size="524288" crc="5c0f694b" sha1="ca346d6b249bb7a3015f016d25bfb3050360c8ec"/>
		<rom type="prog2" name="epr-20128.19" size="524288" crc="ffbdbdc5" sha1="3cbcc5ce3fcb563f11dc87ac514de2325c6cc9f2"/>
		<rom type="prog3" name="epr-20129.20" size="524288" crc="0db897ce" sha1="68f5005082c69fab254d43485669dd6b95a6cc9b"/>
		<rom type="crom00" name="mpr-20130.1" size="2097152" crc="19e1eaca" sha1="e63afe7d8f5e653d0efd026fe20da0850f908d5e"/>
		<rom type="crom01" name="mpr-20131.2" size="2097152" crc="d86ec71b" sha1="da8ffb1a8000b8e656893c29dad8458e04c91df6"/>
		<rom type="crom02" name="mpr-20132.3" size="2097152" crc="91ebc0fb" sha1="0c37d29c15ec7137dd5398c010a289ffce9ee1e8"/>
		<rom type="crom03" name="mpr-20133.4" size="2097152" crc="d9a10a89" sha1="a1c1dff2cde54cd128690bb5896448786e5243b9"/>
		<rom type="crom10" name="mpr-19197.5" size="4194304" crc="a22d76c9" sha1="ad2d67a62436ccc6479e2a218ab09d2fc22c367d"/>
		<rom type="crom11" name="mpr-19198.6" size="4194304" crc="d8ee5032" sha1="3e9274142874ace76dba2bc9b5351cfdfb3a50cd"/>
		<rom type="crom12" name="mpr-19199.7" size="4194304" crc="9f80d6fe" sha1="97b9076d413e28d00e9c45fcc7dad6f534ca8874"/>
		<rom type="crom13" name="mpr-19200.8" size="4194304" crc="74941091" sha1="914db3955f355779147d86446f5976121191ea6d"/>
		<rom type="crom20" name="mpr-19201.9" size="4194304" crc="7c4a8c31" sha1="473b7bef932d7d54a5dc06bd80d286f2e2e96d44"/>
		<rom type="crom21" name="mpr-19202.10" size="4194304" crc="aaa086c6" sha1="01871c8e5454aed80e907fde199cfb23a57aa1c2"/>
		<rom type="crom22" name="mpr-19203.11" size="4194304" crc="0afa6334" sha1="1bb70e823fb6e05df069cbfafed2e57bda8776b9"/>
		<rom type="crom23" name="mpr-19204.12" size="4194304" crc="2f93310a" sha1="3dfc5b72a78967d7772da4098adb41f18b5294d4"/>
		<rom type="crom30" name="mpr-19205.13" size="4194304" crc="199c328e" sha1="1ef1f09ff1f5253bf03e06c5b6e42be9599b9ea5"/>
		<rom type="crom31" name="mpr-19206.14" size="4194304" crc="71a98d73" sha1="dda617f9f5f986e3369fa3d3090c423eefdf913c"/>
		<rom type="crom32" name="mpr-19207.15" size="4194304" crc="2ce1612d" sha1="736f559d460f0069c7a2d5ba7cddf9135737d6e2"/>
		<rom type="crom33" name="mpr-19208.16" size="4194304" crc="08f30f71" sha1="393525b19cdecddfbd62c6209203db5f3edfd9a8"/>
		<rom type="vrom00" name="mpr-19211.26" size="2097152" crc="9c8f5df1" sha1="d47c8bd0189c8e617a3ed9f75ee3812a229f56c0"/>
		<rom type="vrom01" name="mpr-19212.27" size="2097152" crc="75036234" sha1="01a20a6a62408017bff8f2e76dbd21c00275bc70"/>
		<rom type="vrom02" name="mpr-19213.28" size="2097152" crc="67b123cf" sha1="b84c4f83c25edcc8ac929d3f9cf51da713045071"/>
		<rom type="vrom03" name="mpr-19214.29" size="2097152" crc="a6f5576b" sha1="e994b3ef8e6eb07e8f3bbe474410c06d6c42354b"/>
		<rom type="vrom04" name="mpr-19215.30" size="2097152" crc="c6fd9f0d" sha1="1f3299706d6ac73836c069a7ed2866d412f60369"/>
		<rom type="vrom05" name="mpr-19216.31" size="2097152" crc="201bb1ed" sha1="7ffd72ff56159529d74f01f8da0ba4798f109806"/>
		<rom type="vrom06" name="mpr-19217.32" size="2097152" crc="4dadd41a" sha1="7a1e0908962afcfc737132478c0e45d153d94ecb"/>
		<rom type="vrom07" name="mpr-19218.33" size="2097152" crc="cff91953" sha1="41e95704a65958377c3bbd9d00d90a5ad4552f66"/>
		<rom type="vrom10" name="mpr-19219.34" size="2097152" crc="c610d521" sha1="cb146fe78d89176e9dd5c773644614cdc2ef57ce"/>
		<rom type="vrom11" name="mpr-19220.35" size="2097152" crc="e62924d0" sha1="4d1ac11a5977a4e9cf942c9f1204960c0a895347"/>
		<rom type="vrom12" name="mpr-19221.36" size="2097152" crc="24f83e3c" sha1="c587428fa47e849881bf45487af086db6b09264e"/>
		<rom type="vrom13" name="mpr-19222.37" size="2097152" crc="61a6aa7d" sha1="cc26020b2f904f68822111073b595ee0cc8b2e0c"/>
		<rom type="vrom14" name="mpr-19223.38" size="2097152" crc="1a8c1980" sha1="43b8efb019c8a20fe38f95050fe60dfe9bf322f0"/>
		<rom type="vrom15" name="mpr-19224.39" size="2097152" crc="0a79a1bd" sha1="1df71cf77ea8611462380a449eb99199664b3da3"/>
		<rom type="vrom16" name="mpr-19225.40" size="2097152" crc="91a985eb" sha1="5a842a260e4a78f5463222db44f13b068fa70b23"/>
		<rom type="vrom17" name="mpr-19226.41" size="2097152" crc="00091722" sha1="ef86db36b4b91a66b3e401c3c91735b9d28da2e2"/>
		<rom type="sprog" name="epr-19231.21" size="131072" crc="f2ae2558" sha1="7ab5fc508ffd1b0c9f3e70f4d3edeae44e3a0dc4"/>
		<rom type="srom0" name="mpr-19209.22" size="4194304" crc="3715e38c" sha1="b11dbf8a5840990e9697c53b4796cd70ad91f6a1"/>
		<rom type="srom1" name="mpr-19210.24" size="4194304" crc="c03d6502" sha1="4ca49fe5dd5105ca5f78f4740477beb64137d4be"/>
	</game>
	<game name="bass">
		<description>Sega Bass Fishing</description>
		<year>1997</year>
		<manufacturer>Sega</manufacturer>
		<step>1.0</step>
		<bridge>mpc106</bridge>
		
		<patch size="32" address="7999a8" data="60000000"/>
		<patch size="32" address="7999c8" data="60000000"/>
		<patch size="32" address="799980" data="60000000"/>
		<patch size="32" address="78ac14" data="60000000"/>
		<patch size="32" address="78abf8" data="60000000"/>
		<patch size="32" address="100174" data="60000000"/>
		<patch size="32" address="791788" data="60000000"/>
		
		<rom type="prog0" name="epr-20643.17" size="524288" crc="daf02716" sha1="b968f8ca602c78b9ca49969ff01f9440f175049a"/>
		<rom type="prog1" name="epr-20644.18" size="524288" crc="c28db2b6" sha1="0b12fe9e5189714b1aca79c4bba4be57a9e0d5fd"/>
		<rom type="prog2" name="epr-20645.19" size="524288" crc="8eefa2b0" sha1="130ce2a58daa2eba6e56e1f49488017ab871bb7d"/>
		<rom type="prog3" name="epr-20646.20" size="524288" crc="d740ae06" sha1="f6c00b9f3f8cf67c8bd8fff73c64bc0c14d364c4"/>
		<rom type="crom00" name="mpr-20256.1" size="4194304" crc="115302ac" sha1="45f60aa9f91c9a5821a14647e5ac4d53caf71d5f"/>
		<rom type="crom01" name="mpr-20257.2" size="4194304" crc="025bc06d" sha1="e774021d8d884871e840100ba6f4c16299233a51"/>
		<rom type="crom02" name="mpr-20258.3" size="4194304" crc="7b78b071" sha1="f2b29a1238c9eae0a7a68c91a9728ac31f05ef7d"/>
		<rom type="crom03" name="mpr-20259.4" size="4194304" crc="40052562" sha1="2361fd299b76b1c0d112f1fed85bde16e1564382"/>
		<rom type="crom10" name="mpr-20260.5" size="4194304" crc="c56b4c10" sha1="a0a81d4f05df5b8584c2dca53993c01a35d38812"/>
		<rom type="crom11" name="mpr-20261.6" size="4194304" crc="b1e9d44a" sha1="dfe8c5ed848afd48040775bb5a440c590188272c"/>
		<rom type="crom12" name="mpr-20262.7" size="4194304" crc="52b0674d" sha1="c9f817b46dc7fcd04dfc2bbc4b1d82b1f41fe258"/>
		<rom type="crom13" name="mpr-20263.8" size="4194304" crc="1cf4cba9" sha1="2884bb00990ab4bdad0d524937123c2936523cbb"/>
		<rom type="crom20" name="mpr-20264.9" size="4194304" crc="8d995196" sha1="ff410d80353956ee8e770d7b9e9dabac87ee76cc"/>
		<rom type="crom21" name="mpr-20265.10" size="4194304" crc="28f76e3e" sha1="5446e0a0df60d77112bd71c726291fdbba7df284"/>
		<rom type="crom22" name="mpr-20266.11" size="4194304" crc="abd2db85" sha1="ebe752071562c532e6ad494f285ff4d0b5050611"/>
		<rom type="crom23" name="mpr-20267.12" size="4194304" crc="48989191" sha1="ddbf787ec5dae298ab29847f117eae2ce1ff935e"/>
		<rom type="vrom00" name="mpr-20270.26" size="2097152" crc="df68a7a7" sha1="5d610962dd87c010a094fe2ce8d13408595b4ae4"/>
		<rom type="vrom01" name="mpr-20271.27" size="2097152" crc="4b01c3a4" sha1="8d47109e7f410c9d34d57b22adfe1c3092e70074"/>
		<rom type="vrom02" name="mpr-20272.28" size="2097152" crc="a658da23" sha1="b96270c64cf75625960fa7c03411af595880353f"/>
		<rom type="vrom03" name="mpr-20273.29" size="2097152" crc="577e9ffa" sha1="b004fa10a073e6f4715b417da817051752db5636"/>
		<rom type="vrom04" name="mpr-20274.30" size="2097152" crc="7c7056ae" sha1="79f6e0ac65f9e80875946b2e73cf9437ecf73407"/>
		<rom type="vrom05" name="mpr-20275.31" size="2097152" crc="e739f77a" sha1="6547c4bc0925af6e07beab54377a174a9c17e9fa"/>
		<rom type="vrom06" name="mpr-20276.32" size="2097152" crc="cbf966c0" sha1="7c63506d01b52c8ab86fe0dc9ac774e2d540f7c5"/>
		<rom type="vrom07" name="mpr-20277.33" size="2097152" crc="9c75200b" sha1="b39f571eeab11a619ab964d78a2ba0aa7b1dd24f"/>
		<rom type="vrom10" name="mpr-20278.34" size="2097152" crc="db3991ba" sha1="7854a047741042f087a146882e27f2624f1f9e98"/>
		<rom type="vrom11" name="mpr-20279.35" size="2097152" crc="995a11b8" sha1="eddd32fc3688d12458c5ffb3b3e70459947889a2"/>
		<rom type="vrom12" name="mpr-20280.36" size="2097152" crc="c2c8f9f5" sha1="dd30c1fbece0a3dc8dad2d9d87e58a9f3798f4a2"/>
		<rom type="vrom13" name="mpr-20281.37" size="2097152" crc="da84b967" sha1="dfc13942adc9cf438e70470cb17f4d1f846c4c1a"/>
		<rom type="vrom14" name="mpr-20282.38" size="2097152" crc="1869ff49" sha1="1368123edfd9c93d1ee591bf40ea110deeac88cf"/>
		<rom type="vrom15" name="mpr-20283.39" size="2097152" crc="7d8fb469" sha1="ad95fec786e9181d91a6ea18808bbf2772e9be6a"/>
		<rom type="vrom16" name="mpr-20284.40" size="2097152" crc="5c7f3a6f" sha1="d242bc7ad213a79203cd6a060229c356ec0867e7"/>
		<rom type="vrom17" name="mpr-20285.41" size="2097152" crc="4aadc573" sha1="65aef06c8c48196a0c1f630529ae2248323c5747"/>
		<rom type="sprog" name="epr-20313.21" size="524288" crc="863a7857" sha1="72384dc6d7613806ab6bb84d935a3b0497e9e9d2"/>
		<rom type="srom0" name="mpr-20268.22" size="4194304" crc="3631e93e" sha1="3991d6cf03e4f39733d467c483857eac874505d1"/>
		<rom type="srom1" name="mpr-20269.24" size="4194304" crc="105a3181" sha1="022cbce1d01366461a584ff6225ded40bcb9000b"/>
	</game>
	<game name="getbass" parent="bass">
		<description>Get Bass</description>
		<year>1997</year>
		<manufacturer>Sega</manufacturer>
		<step>1.0</step>
		<rom type="prog0" name="epr-20309.17" size="524288" crc="a42e1033" sha1="a834eb973e9529338413220a2d8e66ce98d6cb31"/>
		<rom type="prog1" name="epr-20310.18" size="524288" crc="4efcddc9" sha1="d1362c2a844b605901083e875a6aad817401eb0a"/>
		<rom type="prog2" name="epr-20311.19" size="524288" crc="f721050d" sha1="320a0bd29ac530760d941e54fec2dbc923d6d0f2"/>
		<rom type="prog3" name="epr-20312.20" size="524288" crc="9d8b8b58" sha1="6e91aa6a56593e3df8909d149b0c8da189bfbe82"/>
		<rom type="crom00" name="mpr-20256.1" size="4194304" crc="115302ac" sha1="45f60aa9f91c9a5821a14647e5ac4d53caf71d5f"/>
		<rom type="crom01" name="mpr-20257.2" size="4194304" crc="025bc06d" sha1="e774021d8d884871e840100ba6f4c16299233a51"/>
		<rom type="crom02" name="mpr-20258.3" size="4194304" crc="7b78b071" sha1="f2b29a1238c9eae0a7a68c91a9728ac31f05ef7d"/>
		<rom type="crom03" name="mpr-20259.4" size="4194304" crc="40052562" sha1="2361fd299b76b1c0d112f1fed85bde16e1564382"/>
		<rom type="crom10" name="mpr-20260.5" size="4194304" crc="c56b4c10" sha1="a0a81d4f05df5b8584c2dca53993c01a35d38812"/>
		<rom type="crom11" name="mpr-20261.6" size="4194304" crc="b1e9d44a" sha1="dfe8c5ed848afd48040775bb5a440c590188272c"/>
		<rom type="crom12" name="mpr-20262.7" size="4194304" crc="52b0674d" sha1="c9f817b46dc7fcd04dfc2bbc4b1d82b1f41fe258"/>
		<rom type="crom13" name="mpr-20263.8" size="4194304" crc="1cf4cba9" sha1="2884bb00990ab4bdad0d524937123c2936523cbb"/>
		<rom type="crom20" name="mpr-20264.9" size="4194304" crc="8d995196" sha1="ff410d80353956ee8e770d7b9e9dabac87ee76cc"/>
		<rom type="crom21" name="mpr-20265.10" size="4194304" crc="28f76e3e" sha1="5446e0a0df60d77112bd71c726291fdbba7df284"/>
		<rom type="crom22" name="mpr-20266.11" size="4194304" crc="abd2db85" sha1="ebe752071562c532e6ad494f285ff4d0b5050611"/>
		<rom type="crom23" name="mpr-20267.12" size="4194304" crc="48989191" sha1="ddbf787ec5dae298ab29847f117eae2ce1ff935e"/>
		<rom type="vrom00" name="mpr-20270.26" size="2097152" crc="df68a7a7" sha1="5d610962dd87c010a094fe2ce8d13408595b4ae4"/>
		<rom type="vrom01" name="mpr-20271.27" size="2097152" crc="4b01c3a4" sha1="8d47109e7f410c9d34d57b22adfe1c3092e70074"/>
		<rom type="vrom02" name="mpr-20272.28" size="2097152" crc="a658da23" sha1="b96270c64cf75625960fa7c03411af595880353f"/>
		<rom type="vrom03" name="mpr-20273.29" size="2097152" crc="577e9ffa" sha1="b004fa10a073e6f4715b417da817051752db5636"/>
		<rom type="vrom04" name="mpr-20274.30" size="2097152" crc="7c7056ae" sha1="79f6e0ac65f9e80875946b2e73cf9437ecf73407"/>
		<rom type="vrom05" name="mpr-20275.31" size="2097152" crc="e739f77a" sha1="6547c4bc0925af6e07beab54377a174a9c17e9fa"/>
		<rom type="vrom06" name="mpr-20276.32" size="2097152" crc="cbf966c0" sha1="7c63506d01b52c8ab86fe0dc9ac774e2d540f7c5"/>
		<rom type="vrom07" name="mpr-20277.33" size="2097152" crc="9c75200b" sha1="b39f571eeab11a619ab964d78a2ba0aa7b1dd24f"/>
		<rom type="vrom10" name="mpr-20278.34" size="2097152" crc="db3991ba" sha1="7854a047741042f087a146882e27f2624f1f9e98"/>
		<rom type="vrom11" name="mpr-20279.35" size="2097152" crc="995a11b8" sha1="eddd32fc3688d12458c5ffb3b3e70459947889a2"/>
		<rom type="vrom12" name="mpr-20280.36" size="2097152" crc="c2c8f9f5" sha1="dd30c1fbece0a3dc8dad2d9d87e58a9f3798f4a2"/>
		<rom type="vrom13" name="mpr-20281.37" size="2097152" crc="da84b967" sha1="dfc13942adc9cf438e70470cb17f4d1f846c4c1a"/>
		<rom type="vrom14" name="mpr-20282.38" size="2097152" crc="1869ff49" sha1="1368123edfd9c93d1ee591bf40ea110deeac88cf"/>
		<rom type="vrom15" name="mpr-20283.39" size="2097152" crc="7d8fb469" sha1="ad95fec786e9181d91a6ea18808bbf2772e9be6a"/>
		<rom type="vrom16" name="mpr-20284.40" size="2097152" crc="5c7f3a6f" sha1="d242bc7ad213a79203cd6a060229c356ec0867e7"/>
		<rom type="vrom17" name="mpr-20285.41" size="2097152" crc="4aadc573" sha1="65aef06c8c48196a0c1f630529ae2248323c5747"/>
		<rom type="sprog" name="epr-20313.21" size="524288" crc="863a7857" sha1="72384dc6d7613806ab6bb84d935a3b0497e9e9d2"/>
		<rom type="srom0" name="mpr-20268.22" size="4194304" crc="3631e93e" sha1="3991d6cf03e4f39733d467c483857eac874505d1"/>
		<rom type="srom1" name="mpr-20269.24" size="4194304" crc="105a3181" sha1="022cbce1d01366461a584ff6225ded40bcb9000b"/>
	</game>
	<game name="scud">
		<description>Scud Race (Australia)</description>
		<year>1996</year>
		<manufacturer>Sega</manufacturer>
		<step>1.5</step>
		
		<input type="button01" mapping="p1_button_1"/>
		<input type="button02" mapping="p1_button_2"/>
		<input type="button03" mapping="p1_button_3"/>
		<input type="button04" mapping="p1_button_4"/>
		<input type="analog1" center="128" mapping="analog_axis_1"/>
		<input type="analog2" mapping="analog_axis_3"/>
		<input type="analog3" mapping="analog_axis_4"/>
		
		<patch size="32" address="71275c" data="60000000"/>
		<patch size="32" address="71277c" data="60000000"/>
		<patch size="32" address="74072c" data="60000000"/>
		
		<rom type="prog0" name="epr-19731.17" size="524288" crc="3ee6447e" sha1="124697791d90c1b352dd6e33bd3b45535aa92bb5"/>
		<rom type="prog1" name="epr-19732.18" size="524288" crc="23e864bb" sha1="0f34d963ee681ca1006f3dec12b593d961e3e442"/>
		<rom type="prog2" name="epr-19733.19" size="524288" crc="6565e29a" sha1="4fb4f3e77fa46a825900a63095307714e71c08f3"/>
		<rom type="prog3" name="epr-19734.20" size="524288" crc="be897336" sha1="690e17f2f9a5fbe63686d197552a298efcc8c8c5"/>
		<rom type="crom00" name="mpr-19658.01" size="4194304" crc="d523235c" sha1="0dbfe746b2bdc185768d82c50a329c4c58ad4a29"/>
		<rom type="crom01" name="mpr-19659.02" size="4194304" crc="c47e7002" sha1="9644694e6d117564f92650f32f94ce4d7b5523fa"/>
		<rom type="crom02" name="mpr-19660.03" size="4194304" crc="d999c935" sha1="ef5429e90314d7a789d8ccbad4d0efaeaff9741a"/>
		<rom type="crom03" name="mpr-19661.04" size="4194304" crc="8e3fd241" sha1="df2596f483c759f068c75337320d369d80189ea1"/>
		<rom type="crom10" name="mpr-19662.05" size="4194304" crc="3c700eff" sha1="2ebb149a3d8a9de95afe091b3a1776f4dc3fc579"/>
		<rom type="crom11" name="mpr-19663.06" size="4194304" crc="f6af1ca4" sha1="c78237b8f568792202d927ba0af86df6df80f87a"/>
		<rom type="crom12" name="mpr-19664.07" size="4194304" crc="b9d11294" sha1="69b6f5708f423fb11337184a3646597356554058"/>
		<rom type="crom13" name="mpr-19665.08" size="4194304" crc="f97c78f9" sha1="39aa69e365bf597e5e9185aaf4a044b485ebad8d"/>
		<rom type="crom20" name="mpr-19666.09" size="4194304" crc="b53dc97f" sha1="a4fbc7aade153e6f5fc1dd40ba97d462f643c2c4"/>
		<rom type="crom21" name="mpr-19667.10" size="4194304" crc="a8676799" sha1="78734b194e2797ac7efc40f3d0a2ff09dc93409e"/>
		<rom type="crom22" name="mpr-19668.11" size="4194304" crc="0b4dd8d5" sha1="b5668ce7ac5a4ac844a0a5a07df9649df9ad9615"/>
		<rom type="crom23" name="mpr-19669.12" size="4194304" crc="cdc43c61" sha1="b096d0eb302a9285a8ee396fdbd7b8c546049fd4"/>
		<rom type="vrom00" name="mpr-19672.26" size="2097152" crc="588c29fd" sha1="5f58c885b506592106aa15208fc1db9d55ab4481"/>
		<rom type="vrom01" name="mpr-19673.27" size="2097152" crc="156abaa9" sha1="6ef9c042e9ee34090192c1c99c98d19f18efcfba"/>
		<rom type="vrom02" name="mpr-19674.28" size="2097152" crc="c7b0f98c" sha1="632dbc4cb225d91c82f6a1874517ed0b03b7a0c5"/>
		<rom type="vrom03" name="mpr-19675.29" size="2097152" crc="ff113396" sha1="af90bb696a3c1585318150cb83ea2ed85cdb67a1"/>
		<rom type="vrom04" name="mpr-19676.30" size="2097152" crc="fd852ead" sha1="854204c33aec8fb9c014db06e4106be37ecdaf0d"/>
		<rom type="vrom05" name="mpr-19677.31" size="2097152" crc="c6ac0347" sha1="c792da72af8bf9d011305c9ab7a6230b9e2c5316"/>
		<rom type="vrom06" name="mpr-19678.32" size="2097152" crc="b8819cfe" sha1="b99f8d0626bc38c75058e94d2461dbec6029589d"/>
		<rom type="vrom07" name="mpr-19679.33" size="2097152" crc="e126c3e3" sha1="5440540c2432a9ff5bd8e36467af46c456d16844"/>
		<rom type="vrom10" name="mpr-19680.34" size="2097152" crc="00ea5cef" sha1="3aed46182c0e99c0b72b26c718e2fa20fa7d2e44"/>
		<rom type="vrom11" name="mpr-19681.35" size="2097152" crc="c949325f" sha1="146de7abf764adc1840b84294cbd473f191cbcb8"/>
		<rom type="vrom12" name="mpr-19682.36" size="2097152" crc="ce5ca065" sha1="2f518186b29e7cf5fa1c6b036427b8015cfb681e"/>
		<rom type="vrom13" name="mpr-19683.37" size="2097152" crc="e5856419" sha1="3f8f5b8b36d417090955d34553dcf6d8d9f34558"/>
		<rom type="vrom14" name="mpr-19684.38" size="2097152" crc="56f6ec97" sha1="dfd251dba77b39342457036fcbe4683d24029600"/>
		<rom type="vrom15" name="mpr-19685.39" size="2097152" crc="42b49304" sha1="4e185d0f97de44a25b5f982a46f0c3d1dab406c2"/>
		<rom type="vrom16" name="mpr-19686.40" size="2097152" crc="84eed592" sha1="cc03094770945096d81bc981bff77b540452b045"/>
		<rom type="vrom17" name="mpr-19687.41" size="2097152" crc="776ce694" sha1="d1e56ebd0011aa3a54a5829c6bd0f5343b283fa0"/>
		<rom type="sprog" name="epr-19692.21" size="524288" crc="a94f5521" sha1="22b6a17d44fec8bf796e1790bcabc41f34c89baf"/>
		<rom type="srom0" name="mpr-19670.22" size="4194304" crc="bd31cc06" sha1="d1c85d0cf79b92de5bcbe20dfb8b626ad72de019"/>
		<rom type="srom1" name="mpr-19671.24" size="4194304" crc="8e8526ab" sha1="3d2cbb09bd185660feea4dd80bee5af2e2a19aa6"/>
		<rom type="dsbprog" name="epr-19612.2" size="131072" crc="13978fd4" sha1="bb597914a34308376239afab6e04fc231e39e379"/>
		<rom type="dsbrom0" name="mpr-19603.57" size="2097152" crc="b1b1765f" sha1="cdcb4d6e6507322f84ac5153b386c3eb5d031e22"/>
		<rom type="dsbrom1" name="mpr-19604.58" size="2097152" crc="6ac85b49" sha1="3e74ae6e9ac7b208e2cd5ebdf80bb3cee19d436d"/>
		<rom type="dsbrom2" name="mpr-19605.59" size="2097152" crc="bec891eb" sha1="357849d2842ac77f9945eb4a0ca89253e474f617"/>
		<rom type="dsbrom3" name="mpr-19606.60" size="2097152" crc="adad46b2" sha1="360b23870f1d15ab527fae1bb731da6e7a8b19c1"/>
	</game>
	<game name="scuda" parent="scud">
		<description>Scud Race (Export)</description>
		<year>1996</year>
		<manufacturer>Sega</manufacturer>
		<step>1.5</step>
		
		<input type="button01" mapping="p1_button_1"/>
		<input type="button02" mapping="p1_button_2"/>
		<input type="button03" mapping="p1_button_3"/>
		<input type="button04" mapping="p1_button_4"/>
		<input type="analog1" center="128" mapping="analog_axis_1"/>
		<input type="analog2" mapping="analog_axis_3"/>
		<input type="analog3" mapping="analog_axis_4"/>
		
		<patch size="32" address="71275c" data="60000000"/>
		<patch size="32" address="71277c" data="60000000"/>
		<patch size="32" address="74072c" data="60000000"/>
		
		<rom type="prog0" name="epr-19688.17" size="524288" crc="a4c85103" sha1="b2e57f86d0a49e3e88fa7d6a77bbd99039c034bb"/>
		<rom type="prog1" name="epr-19689.18" size="524288" crc="cbce6d62" sha1="b6051af013ee80406cfadb0c8acf24b8825ccaf2"/>
		<rom type="prog2" name="epr-19690.19" size="524288" crc="25f007fe" sha1="d3814637f6278c30ea277e30e66ad06e37d37e15"/>
		<rom type="prog3" name="epr-19691.20" size="524288" crc="83523b89" sha1="c881c71c961948c8ff3fab33e1db23cff4db0ed8"/>
		<rom type="crom00" name="mpr-19658.01" size="4194304" crc="d523235c" sha1="0dbfe746b2bdc185768d82c50a329c4c58ad4a29"/>
		<rom type="crom01" name="mpr-19659.02" size="4194304" crc="c47e7002" sha1="9644694e6d117564f92650f32f94ce4d7b5523fa"/>
		<rom type="crom02" name="mpr-19660.03" size="4194304" crc="d999c935" sha1="ef5429e90314d7a789d8ccbad4d0efaeaff9741a"/>
		<rom type="crom03" name="mpr-19661.04" size="4194304" crc="8e3fd241" sha1="df2596f483c759f068c75337320d369d80189ea1"/>
		<rom type="crom10" name="mpr-19662.05" size="4194304" crc="3c700eff" sha1="2ebb149a3d8a9de95afe091b3a1776f4dc3fc579"/>
		<rom type="crom11" name="mpr-19663.06" size="4194304" crc="f6af1ca4" sha1="c78237b8f568792202d927ba0af86df6df80f87a"/>
		<rom type="crom12" name="mpr-19664.07" size="4194304" crc="b9d11294" sha1="69b6f5708f423fb11337184a3646597356554058"/>
		<rom type="crom13" name="mpr-19665.08" size="4194304" crc="f97c78f9" sha1="39aa69e365bf597e5e9185aaf4a044b485ebad8d"/>
		<rom type="crom20" name="mpr-19666.09" size="4194304" crc="b53dc97f" sha1="a4fbc7aade153e6f5fc1dd40ba97d462f643c2c4"/>
		<rom type="crom21" name="mpr-19667.10" size="4194304" crc="a8676799" sha1="78734b194e2797ac7efc40f3d0a2ff09dc93409e"/>
		<rom type="crom22" name="mpr-19668.11" size="4194304" crc="0b4dd8d5" sha1="b5668ce7ac5a4ac844a0a5a07df9649df9ad9615"/>
		<rom type="crom23" name="mpr-19669.12" size="4194304" crc="cdc43c61" sha1="b096d0eb302a9285a8ee396fdbd7b8c546049fd4"/>
		<rom type="vrom00" name="mpr-19672.26" size="2097152" crc="588c29fd" sha1="5f58c885b506592106aa15208fc1db9d55ab4481"/>
		<rom type="vrom01" name="mpr-19673.27" size="2097152" crc="156abaa9" sha1="6ef9c042e9ee34090192c1c99c98d19f18efcfba"/>
		<rom type="vrom02" name="mpr-19674.28" size="2097152" crc="c7b0f98c" sha1="632dbc4cb225d91c82f6a1874517ed0b03b7a0c5"/>
		<rom type="vrom03" name="mpr-19675.29" size="2097152" crc="ff113396" sha1="af90bb696a3c1585318150cb83ea2ed85cdb67a1"/>